backend:
  name: git-gateway
  repo: whoisgina/dat-foundation-website
  branch: master

publish_mode: editorial_workflow
media_folder: ".vuepress/public/upload"
public_folder: "../../"

collections:
  - name: "Home" # Used in routes, e.g., /admin/collections/blog
    label: "Home" # Used in the UI
    folder: "site/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
